=== nojhan/stripit/striped/strip.dtd
<!ELEMENT strip (case+)>
<!ELEMENT case (personnage*, bulle*)>
<!ELEMENT personnage (bulle*)>
<!ELEMENT bulle (#PCDATA)>

<!ATTLIST strip x CDATA "0">
<!ATTLIST strip y CDATA "0">
<!ATTLIST strip height CDATA "480">
<!ATTLIST strip licence CDATA #FIXED "CC-BY-SA">
<!ATTLIST strip author CDATA #IMPLIED>
<!ATTLIST case fond CDATA #IMPLIED>
<!ATTLIST case width CDATA "600">
<!ATTLIST personnage x CDATA "0">
<!ATTLIST personnage y CDATA "0">
<!ATTLIST personnage pos CDATA "gauche">
<!ATTLIST personnage url CDATA #REQUIRED>
<!ATTLIST bulle x CDATA "0">
<!ATTLIST bulle y CDATA "0">
<!ATTLIST bulle width CDATA "200">
<!ATTLIST bulle contour CDATA "true">
<!ATTLIST bulle size CDATA "15">

=== nojhan/stripit/striped/geekscottes_133.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE strip SYSTEM "http://mcmic.free.fr/GeekscottesMaker/strip.dtd">

<strip x="10" y="10" height="225">
	<case fond="fonds/laptop.svg#layer1" width="307">
		<personnage url="persos/gnu/vert.svg#layer1" x="0" y="103" pos="gauche">
			<bulle x="50" y="10" width="155" contour="true">Une fois j'ai eu l'auriculaire cassé</bulle>
			<bulle x="100" y="60" width="150" contour="true">Bilan : 15 jour d'arret de travail</bulle>
		</personnage>
		<personnage url="persos/mozilla/normal.svg#layer1" x="155" y="110" pos="gauche">
		</personnage>
	</case>
	<case fond="fonds/laptop.svg#layer1" width="307">
		<personnage url="persos/gnu/vert.svg#layer1" x="0" y="103" pos="gauche">
		</personnage>
		<personnage url="persos/mozilla/choque.svg#layer1" x="155" y="110" pos="gauche">
			<bulle x="120" y="40" width="150" contour="true">2 SEMAINES !?</bulle>
		</personnage>
	</case>
	<case fond="fonds/laptop.svg#layer1" width="307">
		<personnage url="persos/gnu/vert.svg#layer1" x="0" y="103" pos="gauche">
		</personnage>
		<personnage url="persos/mozilla/sourcil.svg#layer1" x="155" y="110" pos="gauche">
			<bulle x="120" y="30" width="150" contour="true">Mais pourquoi tu as repris si tôt ?</bulle>
		</personnage>
	</case>
	<case fond="fonds/laptop.svg#layer1" width="307">
		<personnage url="persos/gnu/vert_content.svg#layer1" x="0" y="103" pos="gauche">
			<bulle x="30" y="20" width="200" contour="true">J'en ai profité pour passer sous Vim...</bulle>
		</personnage>
		<personnage url="persos/mozilla/goutte.svg#layer1" x="155" y="110" pos="gauche">
		</personnage>
	</case>
</strip>

=== nojhan/stripit/striped/strip.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE strip SYSTEM "http://mcmic.free.fr/GeekscottesMaker/strip.dtd">

<strip x="10" y="100" height="480">
	<case fond="fonds/bureau.svg#layer1" width="600">
		<personnage url="persos/gnu/rouge.svg#layer1" x="0" y="127" pos="gauche">
			<bulle x="150" y="10" width="100" contour="true">Texte de la bulle</bulle>
		</personnage>
	</case>
	<case fond="fonds/bureau.svg#layer1" width="600">
		<personnage url="persos/w3c/face.svg#layer1" x="0" y="100" pos="gauche">
			<bulle x="150" y="10" width="100" contour="true">Texte de la 2eme bulle</bulle>
		</personnage>
		<bulle x="250" y="210" width="200" contour="true">Bulle sans personnage</bulle>
	</case>
	<case fond="" width="600">
		<personnage url="persos/tux/content.svg#layer1" x="0" y="155" pos="gauche">
			<bulle x="150" y="10" width="100" contour="true">Je kiffe la vie</bulle>
		</personnage>
		<personnage url="persos/gnu/rouge.svg#layer1" x="300" y="127" pos="droite">
			<bulle x="350" y="10" width="100" contour="true">Moi aussi</bulle>
		</personnage>
	</case>
</strip>
